#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# mol2vec documentation build configuration file, created by
# sphinx-quickstart on Mon Oct 30 21:41:26 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('..'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.autosummary',
    'numpydoc']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'mol2vec'
copyright = '2017, Samo Turk, Sabrina Jaeger, Simone Fulle'
author = 'Samo Turk, Sabrina Jaeger, Simone Fulle'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

from mol2vec import __version__ as ver
# The short X.Y version.
version = ver
# The full version, including alpha/beta/rc tags.
release = ver

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'navigation.html',
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'mol2vecdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'mol2vec.tex', 'mol2vec Documentation',
     author, 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'mol2vec', 'mol2vec Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'mol2vec', 'mol2vec Documentation',
     author, 'mol2vec',
     'Mol2vec - an unsupervised machine learning approach to learn vector representations of molecular substructures',
     'Miscellaneous'),
]

# -- Numpydoc

numpydoc_use_plots = True
numpydoc_show_class_members = True
numpydoc_show_inherited_class_members = True
numpydoc_class_members_toctree = True

autosummary_generate = True

# Make sure Docs build properly on Read the Docs
if True:#os.environ.get('READTHEDOCS', None) == 'False':
    # Invoke sphinx-apidoc
    os.system("sphinx-apidoc -f -o rst/ ../mol2vec")

    from unittest.mock import patch, MagicMock

    numpy = MagicMock()
    pandas = MagicMock()
    rdkit = MagicMock()
    tqdm = MagicMock()
    matplotlib = MagicMock()
    joblib = MagicMock()
    gensim = MagicMock()
    seaborn = MagicMock()

    modules = {
                'numpy': numpy,
                'pandas': pandas,
                'tqdm': tqdm,
                'matplotlib': matplotlib,
                'joblib': joblib,
                'gensim': gensim,
                'gensim.models': gensim.models,
                'rdkit': rdkit,
                'rdkit.Chem': rdkit.Chem,
                'rdkit.Chem.AllChem': rdkit.Chem.AllChem,
                'rdkit.Chem.Draw': rdkit.Chem.Draw,
                'rdkit.Chem.Draw.rdDepictor': rdkit.Chem.Draw.rdDepictor,
                'rdkit.Chem.rdDepictor': rdkit.Chem.rdDepictor,
                'rdkit.Chem.PandasTools': rdkit.Chem.PandasTools,
                'seaborn': seaborn,
            }

    p = patch.dict('sys.modules', modules)
    p.start()
